name: Jake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup
      run: sudo apt-get install python3-venv
        python3 -m venv .venv
        source .venv/bin/activate

    - name: Test
      run: python3 -m unittest discover

    - name: Scan
      uses: sonatype-nexus-community/jake-github-action@a3a66b3cdfb01b0394e58f89c7e2b7ef69a5e909
      with:
        condaPipe: true
